// ontology-export.js — converts a sandbox node-link graph (Level 5) into real RDF
// serializations, so players can see the actual syntax their visual model compiles to.
//
// Edge classification is based on the *node kinds* at each end (not just the label text):
//   instance --isA/subClassOf/etc--> class   compiles to rdf:type      (Turtle "a")
//   class    --isA/subClassOf/etc--> class   compiles to rdfs:subClassOf
//   anything else                            compiles to a custom owl:ObjectProperty
// This keeps the export technically correct even though the sandbox itself lets players
// use loose, human labels like "isA" for both kinds of hierarchy edge.

const HIERARCHY_LABELS = ['isa', 'subclassof', 'kindof', 'typeof'];

function isHierarchyLabel(label) {
  return HIERARCHY_LABELS.includes(String(label || '').toLowerCase().replace(/\s+/g, ''));
}

/** Turns free-text like "Alice (Manager)" into a safe PascalCase local name: "AliceManager". */
function toLocalName(label, fallback) {
  const cleaned = String(label || '').replace(/[^a-zA-Z0-9]+/g, ' ').trim();
  if (!cleaned) return fallback;
  const pascal = cleaned.split(' ').filter(Boolean)
    .map(w => w[0].toUpperCase() + w.slice(1)).join('');
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}

/** Turns free-text like "works at" into a safe camelCase property name: "worksAt". */
function toPropName(label) {
  const cleaned = String(label || '').replace(/[^a-zA-Z0-9]+/g, ' ').trim();
  const parts = cleaned.split(' ').filter(Boolean);
  if (!parts.length) return 'relatesTo';
  const [first, ...rest] = parts;
  return first.toLowerCase() + rest.map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

/** Turns a scenario name into a URL/filename-safe slug. */
export function slugify(text) {
  const slug = String(text || 'ontology').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  return slug || 'ontology';
}

function classifyEdge(edge, nodesById) {
  const from = nodesById.get(edge.from);
  const to = nodesById.get(edge.to);
  if (!from || !to) return null;
  // An instance pointing at a class is, by construction in this sandbox's model, a type
  // assertion — regardless of the exact label text a player chose (isA, instanceOf, ...).
  if (from.kind === 'instance' && to.kind === 'class') return 'type';
  // Between two classes, only read it as subClassOf when the label sounds hierarchical;
  // a class-to-class edge can otherwise be a perfectly normal object property (e.g.
  // Product --hasCategory--> Category), so it shouldn't be forced into an inheritance link.
  if (from.kind === 'class' && to.kind === 'class' && isHierarchyLabel(edge.label)) return 'subclass';
  return 'property';
}

/** Assigns every node a stable, de-duplicated local name and classifies every edge. */
function buildModel(nodes, edges) {
  const nodesById = new Map(nodes.map(n => [n.id, n]));
  const used = new Set();
  const nameOf = new Map();
  nodes.forEach(n => {
    const base = toLocalName(n.label, n.kind === 'class' ? 'Class' : 'Instance');
    let name = base;
    let i = 2;
    while (used.has(name)) { name = `${base}${i++}`; }
    used.add(name);
    nameOf.set(n.id, name);
  });
  const classified = edges
    .map(e => ({ ...e, kind: classifyEdge(e, nodesById) }))
    .filter(e => e.kind);
  return { nameOf, classified };
}

/** Generates a real, human-readable RDF Turtle document from the sandbox's nodes/edges. */
export function toTurtle(nodes, edges, scenarioName) {
  const { nameOf, classified } = buildModel(nodes, edges);
  const base = `http://example.org/${slugify(scenarioName)}#`;

  const classNodes = nodes.filter(n => n.kind === 'class');
  const instanceNodes = nodes.filter(n => n.kind === 'instance');
  const subclassEdges = classified.filter(e => e.kind === 'subclass');
  const typeEdges = classified.filter(e => e.kind === 'type');
  const propertyEdges = classified.filter(e => e.kind === 'property');

  const lines = [];
  lines.push(`@prefix : <${base}> .`);
  lines.push('@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .');
  lines.push('@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .');
  lines.push('@prefix owl: <http://www.w3.org/2002/07/owl#> .');
  lines.push('');
  lines.push(`# Ontology generated by Ontology Quest from the "${scenarioName}" sandbox.`);

  if (classNodes.length) {
    lines.push('');
    lines.push('# --- Classes ---');
    classNodes.forEach(n => {
      const name = nameOf.get(n.id);
      const parents = subclassEdges.filter(e => e.from === n.id).map(e => `:${nameOf.get(e.to)}`);
      if (parents.length) {
        lines.push(`:${name} a owl:Class ;`);
        lines.push(`    rdfs:subClassOf ${parents.join(', ')} .`);
      } else {
        lines.push(`:${name} a owl:Class .`);
      }
    });
  }

  const propNames = [...new Set(propertyEdges.map(e => toPropName(e.label)))];
  if (propNames.length) {
    lines.push('');
    lines.push('# --- Object Properties ---');
    propNames.forEach(p => lines.push(`:${p} a owl:ObjectProperty .`));
  }

  if (instanceNodes.length) {
    lines.push('');
    lines.push('# --- Individuals ---');
    instanceNodes.forEach(n => {
      const name = nameOf.get(n.id);
      const types = typeEdges.filter(e => e.from === n.id).map(e => `:${nameOf.get(e.to)}`);
      lines.push(types.length ? `:${name} a ${types.join(', ')} .` : `:${name} a owl:NamedIndividual .`);
    });
  }

  if (propertyEdges.length) {
    lines.push('');
    lines.push('# --- Relationships ---');
    propertyEdges.forEach(e => {
      lines.push(`:${nameOf.get(e.from)} :${toPropName(e.label)} :${nameOf.get(e.to)} .`);
    });
  }

  if (!classNodes.length && !instanceNodes.length) {
    lines.push('');
    lines.push('# Your canvas is empty — add some classes and instances first!');
  }

  return lines.join('\n') + '\n';
}

/** Generates a compact, valid JSON-LD document from the sandbox's nodes/edges. */
export function toJsonLd(nodes, edges, scenarioName) {
  const { nameOf, classified } = buildModel(nodes, edges);
  const base = `http://example.org/${slugify(scenarioName)}#`;

  const subclassEdges = classified.filter(e => e.kind === 'subclass');
  const typeEdges = classified.filter(e => e.kind === 'type');
  const propertyEdges = classified.filter(e => e.kind === 'property');
  const propNames = [...new Set(propertyEdges.map(e => toPropName(e.label)))];

  const context = {
    '@vocab': base,
    rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
    owl: 'http://www.w3.org/2002/07/owl#',
    // "@type": "@id" marks these properties' values as node references (IRIs), not string
    // literals — without it a JSON-LD processor could not tell {"worksAt": "Acme"} apart
    // from a plain text property.
    subClassOf: { '@id': 'rdfs:subClassOf', '@type': '@id' }
  };
  propNames.forEach(p => { context[p] = { '@id': `${base}${p}`, '@type': '@id' }; });

  const graph = nodes.map(n => {
    const name = nameOf.get(n.id);
    const entry = { '@id': name };
    if (n.kind === 'class') {
      const parents = subclassEdges.filter(e => e.from === n.id).map(e => nameOf.get(e.to));
      entry['@type'] = 'owl:Class';
      if (parents.length) entry.subClassOf = parents.length === 1 ? parents[0] : parents;
    } else {
      const types = typeEdges.filter(e => e.from === n.id).map(e => nameOf.get(e.to));
      entry['@type'] = types.length ? (types.length === 1 ? types[0] : types) : 'owl:NamedIndividual';
    }
    propertyEdges.filter(e => e.from === n.id).forEach(e => {
      const p = toPropName(e.label);
      const obj = nameOf.get(e.to);
      if (entry[p] === undefined) entry[p] = obj;
      else if (Array.isArray(entry[p])) entry[p].push(obj);
      else entry[p] = [entry[p], obj];
    });
    return entry;
  });

  return JSON.stringify({ '@context': context, '@graph': graph }, null, 2) + '\n';
}

/** Triggers a same-page, no-backend download of `content` as a file named `filename`. */
export function downloadTextFile(filename, content, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
